# .github/workflows/deploy.yml
name: Deploy to Lightsail

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Upload build to Lightsail
        uses: appleboy/scp-action@master
        with:
          host: 16.176.228.22
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/next-app"

      - name: SSH to move files into /var/www/html
        uses: appleboy/ssh-action@master
        with:
          host: 16.176.228.22
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            cd /home/ubuntu/next-app
            npm install
            npm run build
            pm2 delete all || true
            pm2 start npm --name "next-app" -- start
