name: Deploy to Lightsail

on:
  push:
    branches: [main] # Trigger on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build static site
        run: |
          rm -rf .next out
          npx next build
          mkdir -p out
          cp -r .next/static out/_next
          cp -r public/* out/ || true
          echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; URL=/_next"></head><body></body></html>' > out/index.html

      - name: Deploy to Lightsail via SSH
        uses: appleboy/scp-action@master
        with:
          host: 16.176.228.22
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          source: "out/*"
          target: "/var/www/html"
